function mdlfile = build_closed_loop_model()
%BUILD_CLOSED_LOOP_MODEL Programmatically build arm_closed_loop.slx.
%   mdlfile = BUILD_CLOSED_LOOP_MODEL() creates/overwrites the Simulink
%   model next to this file and returns its full path. The .slx is a build
%   artifact (gitignored); this script is its reviewable source of truth.
%
%   Topology (mentor's whiteboard):
%
%     FromWorkspace cl_Xref ---->(+)Sum_e ----e----> [Controller
%     FromWorkspace cl_VelRef -->(+)Sum_ed --edot-->  MATLAB Function] --u-->
%     [Plant MATLAB Function: M qdd + C qd + G = [u; F_water]] --> 1/s --> x
%       x(1:3) = q  feeds back (-) into Sum_e;  x(5:7) = qd into Sum_ed
%     ToWorkspace: y (=q), err (=e), u, uexo, uhum, phi
%
%   Everything tunable enters through base-workspace variables set per run
%   by Simulink.SimulationInput (run_closed_loop.m): cl_Xref, cl_VelRef,
%   cl_x0, cl_Kp, cl_Kd, cl_alpha, cl_pvec, cl_bs, cl_rigid, cl_Tend.

mdl = 'arm_closed_loop';
here = fileparts(mfilename('fullpath'));
mdlfile = fullfile(here, [mdl '.slx']);

if bdIsLoaded(mdl), close_system(mdl, 0); end
if exist(mdlfile, 'file'), delete(mdlfile); end
new_system(mdl);

% ---- Sources -------------------------------------------------------------
add_block('simulink/Sources/From Workspace', [mdl '/Xref'], ...
    'VariableName', 'cl_Xref', ...
    'OutputAfterFinalValue', 'Holding final value', ...
    'Position', [40 93 130 127]);
add_block('simulink/Sources/From Workspace', [mdl '/VelRef'], ...
    'VariableName', 'cl_VelRef', ...
    'OutputAfterFinalValue', 'Holding final value', ...
    'Position', [40 193 130 227]);

% ---- Error sums (e = Xref - y, edot = VelRef - qd) -------------------------
add_block('simulink/Math Operations/Sum', [mdl '/Sum_e'], ...
    'Inputs', '+-', 'IconShape', 'round', 'Position', [185 95 210 120]);
add_block('simulink/Math Operations/Sum', [mdl '/Sum_ed'], ...
    'Inputs', '+-', 'IconShape', 'round', 'Position', [185 195 210 220]);

% ---- Parameter constants ---------------------------------------------------
cst = {'cKp', 'cl_Kp',    40, 300; ...
       'cKd', 'cl_Kd',    40, 360; ...
       'cAlpha', 'cl_alpha', 40, 420; ...
       'cPvec', 'cl_pvec',  40, 480; ...
       'cBs',  'cl_bs',   540, 300; ...
       'cRigid', 'cl_rigid', 540, 360};
for k = 1:size(cst, 1)
    add_block('simulink/Sources/Constant', [mdl '/' cst{k,1}], ...
        'Value', cst{k,2}, ...
        'Position', [cst{k,3} cst{k,4}-15 cst{k,3}+90 cst{k,4}+15]);
end

% ---- Controller (MATLAB Function block) ------------------------------------
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [mdl '/Controller'], 'Position', [280 80 420 250]);
cfgC = get_param([mdl '/Controller'], 'MATLABFunctionConfiguration');
cfgC.FunctionScript = sprintf([ ...
    'function [u, uexo, uhum] = fcn(e, edot, x, Kp, Kd, alpha, pvec)\n' ...
    '%% PD + gravity comp tracking torque, alpha split (see cl_control_law.m)\n' ...
    '[u, uexo, uhum] = cl_control_law(e, edot, x, Kp, Kd, alpha, pvec);\n' ...
    'end\n']);

% ---- Plant (MATLAB Function block) + integrator -----------------------------
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [mdl '/Plant'], 'Position', [640 80 780 250]);
cfgP = get_param([mdl '/Plant'], 'MATLABFunctionConfiguration');
cfgP.FunctionScript = sprintf([ ...
    'function dx = fcn(x, u, pvec, bs, rigid)\n' ...
    '%% Full nonlinear 4-DOF arm + slosh pendulum (see cl_plant_deriv.m)\n' ...
    'dx = cl_plant_deriv(x, u, pvec, bs, rigid);\n' ...
    'end\n']);

% Explicit port sizes: the Controller/Plant/Integrator loop gives size
% inference no anchor, so every non-scalar port is declared (1-D widths;
% matrices as [r c]). Inside MATLAB Function code 1-D signals appear as
% column vectors.
set_mlfb_sizes(mdl, 'Controller', ...
    {'e', '3'; 'edot', '3'; 'x', '8'; 'Kp', '[3 3]'; 'Kd', '[3 3]'; ...
     'pvec', '15'; 'u', '3'; 'uexo', '3'; 'uhum', '3'});
set_mlfb_sizes(mdl, 'Plant', ...
    {'x', '8'; 'u', '3'; 'pvec', '15'; 'dx', '8'});

add_block('simulink/Continuous/Integrator', [mdl '/Integrator'], ...
    'InitialCondition', 'cl_x0', 'Position', [830 145 870 185]);

% ---- State selectors --------------------------------------------------------
add_block('simulink/Signal Routing/Selector', [mdl '/Sel_q'], ...
    'IndexOptions', 'Index vector (dialog)', 'Indices', '[1 2 3]', ...
    'InputPortWidth', '8', 'Position', [930 90 980 120]);
add_block('simulink/Signal Routing/Selector', [mdl '/Sel_qd'], ...
    'IndexOptions', 'Index vector (dialog)', 'Indices', '[5 6 7]', ...
    'InputPortWidth', '8', 'Position', [930 150 980 180]);
add_block('simulink/Signal Routing/Selector', [mdl '/Sel_phi'], ...
    'IndexOptions', 'Index vector (dialog)', 'Indices', '4', ...
    'InputPortWidth', '8', 'Position', [930 210 980 240]);

% ---- Logging (To Workspace, timeseries) -------------------------------------
tw = {'TW_y',    'y',    1050, 105; ...
      'TW_phi',  'phi',  1050, 225; ...
      'TW_err',  'err',   280, 20; ...
      'TW_u',    'u',     500, 20; ...
      'TW_uexo', 'uexo',  620, 20; ...
      'TW_uhum', 'uhum',  740, 20};
for k = 1:size(tw, 1)
    add_block('simulink/Sinks/To Workspace', [mdl '/' tw{k,1}], ...
        'VariableName', tw{k,2}, 'SaveFormat', 'Timeseries', ...
        'Position', [tw{k,3} tw{k,4}-15 tw{k,3}+100 tw{k,4}+15]);
end

% ---- Wiring -----------------------------------------------------------------
ln = { ...
    'Xref/1',       'Sum_e/1'; ...
    'Sel_q/1',      'Sum_e/2'; ...
    'VelRef/1',     'Sum_ed/1'; ...
    'Sel_qd/1',     'Sum_ed/2'; ...
    'Sum_e/1',      'Controller/1'; ...
    'Sum_ed/1',     'Controller/2'; ...
    'Integrator/1', 'Controller/3'; ...
    'cKp/1',        'Controller/4'; ...
    'cKd/1',        'Controller/5'; ...
    'cAlpha/1',     'Controller/6'; ...
    'cPvec/1',      'Controller/7'; ...
    'Integrator/1', 'Plant/1'; ...
    'Controller/1', 'Plant/2'; ...
    'cPvec/1',      'Plant/3'; ...
    'cBs/1',        'Plant/4'; ...
    'cRigid/1',     'Plant/5'; ...
    'Plant/1',      'Integrator/1'; ...
    'Integrator/1', 'Sel_q/1'; ...
    'Integrator/1', 'Sel_qd/1'; ...
    'Integrator/1', 'Sel_phi/1'; ...
    'Sel_q/1',      'TW_y/1'; ...
    'Sel_phi/1',    'TW_phi/1'; ...
    'Sum_e/1',      'TW_err/1'; ...
    'Controller/1', 'TW_u/1'; ...
    'Controller/2', 'TW_uexo/1'; ...
    'Controller/3', 'TW_uhum/1'};
for k = 1:size(ln, 1)
    add_line(mdl, ln{k,1}, ln{k,2}, 'autorouting', 'on');
end

% ---- Solver / logging config -------------------------------------------------
cl = cl_params();
set_param(mdl, ...
    'StopTime', 'cl_Tend', ...
    'SolverType', 'Variable-step', ...
    'Solver', cl.solver, ...
    'RelTol', sprintf('%g', cl.RelTol), ...
    'AbsTol', sprintf('%g', cl.AbsTol), ...
    'MaxStep', sprintf('%g', cl.MaxStep), ...
    'SaveTime', 'on', 'TimeSaveName', 'tout');

save_system(mdl, mdlfile);
close_system(mdl, 0);
fprintf('Built %s\n', mdlfile);
end

% ------------------------------------------------------------------------
function set_mlfb_sizes(mdl, blk, pairs)
% Declare explicit sizes on a MATLAB Function block's ports (Stateflow API).
ch = find(sfroot, '-isa', 'Stateflow.EMChart', 'Path', [mdl '/' blk]);
assert(~isempty(ch), 'build: MATLAB Function chart "%s" not found', blk);
for k = 1:size(pairs, 1)
    d = ch.find('-isa', 'Stateflow.Data', 'Name', pairs{k, 1});
    assert(~isempty(d), 'build: port "%s" not found in %s', pairs{k, 1}, blk);
    d.Props.Array.Size = pairs{k, 2};
end
end
